export const apiBase = "/api/v1";
const apiFDBUrl = "http://localhost:2610";
export const ROUTES = {
  api: {
    createUser: `${apiBase}/users`,
    login: `${apiBase}/login`,
    logout: `${apiBase}/logout`,
    fetchUser: `${apiBase}/user`,
    produtos: `${apiBase}/produtos`,
    apiFDBStatus: `${apiBase}/fdb/status`,
  },
  url: {
    users: "/users",
    login: "/login",
    logout: "/logout",
    user: "/user",
    produtos: "/produtos",
    apiFDBStatus: "/fdb/status",
  },
  app: {
    icms: "/corrigir-icms",
    ncm: "/corrigir-ncm",
    xml: "/importar-xml",
    atualizarProdutos: "/produtos/atualizar",
    cadastrarProdutos: "/produtos/cadastrar",
  },
  apiFDB: {
    status: `${apiFDBUrl}/status`,
    atualizarProdutos: `${apiFDBUrl}/produtos`,
  },
};

export const protectedRoutes = [
  "/corrigir-icms",
  "/corrigir-ncm",
  "/importar-xml",
  "/produtos/cadastrar",
  "/produtos/atualizar",
];

export const colunasProdutos = [
  "PRO_COD",
  "PRO_NOME",
  "PRO_REF",
  "PRO_BARRA",
  "PRO_SIM",
  "GRU_COD",
  "SUB_COD",
  "PRO_ST",
  "PRO_ST2",
  "PRO_UNI",
  "PRO_EMB",
  "PRO_LOC",
  "PRO_APL",
  "PRO_UNIT",
  "PRO_COM",
  "PRO_CUSTO",
  "PRO_MEDIO",
  "PRO_LUCRO",
  "PRO_VENDA",
  "PRO_MIN",
  "PRO_MAX",
  "PRO_EST",
  "PRO_CAD",
  "ATU_USUA",
  "PRO_FOTO",
  "PRO_CF",
  "PRO_ICMS",
  "PRO_PESO",
  "PRO_IPI",
  "PRO_ICMSC",
  "PRO_SUBS",
  "PRO_SUBSL",
  "PRO_RED",
  "PRO_SIMPLES",
  "PRO_CUSTOADMC",
  "PRO_PIS",
  "PRO_COFINS",
  "PRO_PIS2",
  "PRO_COFINS2",
  "PRO_CUSTOADMV",
  "PRO_ICMSMVA",
  "PRO_SUBS2",
  "PRO_IPI2",
  "PRO_ANTPARC",
  "PRO_DESCANT",
  "PRO_DESCMAX",
  "PRO_GTIN",
  "PRO_DESAT",
  "PRO_CONVER",
  "PRO_STIPI",
  "PRO_STPIS",
  "PRO_STCOFINS",
  "PRO_CSO",
  "PRO_REDV",
  "PRO_STIPI2",
  "PRO_STPIS2",
  "PRO_STCOFINS2",
  "PRO_NAT_REC",
  "CFOP_CODSN",
  "CFOP_CODSD",
  "CFOP_CODED",
  "CFOP_CODEN",
  "PRO_SUBSICMSCREDE",
  "PRO_SUBSICMSCREDS",
  "PRO_SUBSICMSDEBE",
  "PRO_SUBSMVAE",
  "PRO_MODBCST",
  "PRO_SUBICMSDEBE",
  "FAM_COD",
  "SFAM_COD",
  "COD_CTA_ENT",
  "COD_CTA_SAI",
  "PRO_FRACIONADO",
  "PRO_ACOU",
  "PRO_DESONICMS",
  "PRO_PFCPST",
  "PRO_DATAVALID",
  "PRO_ICMSANTCREDITO",
  "PRO_ICMSANTDEBITO",
  "PRO_ST_IBS_CBS",
  "PRO_CLAS_IBS_CBS",
  "PRO_ST_IS",
  "PRO_CLAS_IS",
  "PRO_PRESU_IBS_CBS",
  "PRO_ENT_REF_IBSUF",
  "PRO_ENT_REF_IBSMUN",
  "PRO_ENT_REF_CBS",
  "PRO_ENT_REF_IS",
  "PRO_ENT_REF_IBSUF_RED",
  "PRO_ENT_REF_IBSMUN_RED",
  "PRO_ENT_REF_CBS_RED",
  "PRO_SAI_REF_IBSUF",
  "PRO_SAI_REF_IBSMUN",
  "PRO_SAI_REF_CBS",
  "PRO_SAI_REF_IS",
  "PRO_SAI_REF_IBSUF_RED",
  "PRO_SAI_REF_IBSMUN_RED",
  "PRO_SAI_REF_CBS_RED",
];
